### PR TITLE
ci: build arm64 images

### PR DESCRIPTION
**Pull request by dllg**
Signed-off-by: Daniel Lundborg <daniel.lundborg@sandvik.com>

### CODE REVIEW

**Review by fsouza — COMMENTED** [review]
Hi @dllg, thanks for contributing! This is not enough to build the arm64 images. 

As far as I can tell, we need an arm64 builder to be able to build an arm64 image? I need to do some research to confirm.

**Comment by dllg** [comment]
Ok! Thanks. Main reason I want it is because I'm using an Apple Mac with the new M1 chip.

If you use buildx (buildkit) you can build Multiplatform images: https://github.com/docker/build-push-action/blob/master/docs/advanced/multi-platform.md

**Comment by fsouza** [comment]
@dllg ohh nice, I'll give buildx a shot, thanks for sharing it!

(sorry I'm slow to respond, technically on paternity leave, and checking GH between diapers 😃)

**Comment by Code-Hex** [comment]
What's going on now for arm64?

**Comment by fsouza** [comment]
@Code-Hex we probably need to rework our CI configuration to build linux/arm64 with the info @dllg provided. I can work on this some time next week, but happy to take a PR.

If you're on linux/arm64 and need a docker image, for now you can clone the repo and build it.

**Pull request closed without merging**
