### PR TITLE
Fix some 32-bit incompatibilities

### PR DESCRIPTION
**Pull request by gaul**
This allows fake-gcs-server to work on Raspberry Pi.

### CODE REVIEW

**Review by fsouza — COMMENTED** [review]
Nice catch. Do any of the existing tests fail when running in 32 bits? Thinking of adding it to CI to prevent regressions.

**Comment by gaul** [comment]
Tests pass with this PR.  32-bit is a small niche these days but it usually doesn't take much effort to support.

**Comment by fsouza** [comment]
> Tests pass with this PR.  32-bit is a small niche these days but it usually doesn't take much effort to support.

I know, I just want to make sure we have CI to prevent regressions. do the tests fail without the changes in this PR?

I can investigate some time this week.

**Comment by fsouza** [comment]
ok confirmed that the code won't even compile on 386 (see #517). Will merge this, then rebase #517. Thanks for contributing!

**Review by fsouza — APPROVED** [review]

**Pull request merged**
